name: Auto Merge Master

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check for updates and merge
        run: |
          # Fetch latest changes
          git fetch origin main
          
          # Check if we're behind
          BEHIND=$(git rev-list --count HEAD..origin/main)
          
          if [ "$BEHIND" -gt 0 ]; then
            echo "Branch is $BEHIND commits behind origin/main. Merging..."
            
            # Merge latest master
            git merge origin/main --no-edit
            
            # Push changes
            git push origin HEAD
            
            echo "Successfully merged $BEHIND commits from origin/main"
          else
            echo "Branch is up to date with origin/main"
          fi