name: Auto Update Labeled PRs

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]
  workflow_dispatch: # Allow manual triggering

jobs:
  update-labeled-prs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'auto-update') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update PRs with auto-update label
        uses: actions/github-script@v7
        with:
          script: |
            let prsToUpdate = [];
            
            if (context.eventName === 'pull_request') {
              // If triggered by label addition, only update this specific PR
              if (context.payload.label.name === 'auto-update') {
                prsToUpdate.push({
                  number: context.payload.pull_request.number,
                  title: context.payload.pull_request.title
                });
              }
            } else if (context.eventName === 'push') {
              // If triggered by push to main, find all PRs with auto-update label
              const { data: prs } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
              });

              for (const pr of prs) {
                const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number
                });
                
                const hasAutoUpdateLabel = labels.some(label => label.name === 'auto-update');
                if (hasAutoUpdateLabel) {
                  prsToUpdate.push({
                    number: pr.number,
                    title: pr.title
                  });
                }
              }
            }

            // Update each PR that should be updated
            for (const pr of prsToUpdate) {
              try {
                await github.rest.pulls.updateBranch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number
                });
                
                console.log(`✅ Updated PR #${pr.number}: ${pr.title}`);
                
              } catch (error) {
                console.log(`❌ Could not update PR #${pr.number}: ${error.message}`);
              }
            }
            
            if (prsToUpdate.length === 0) {
              console.log('No PRs with auto-update label found to update');
            }